### PR TITLE
UI overhaul project

### LINKED ISSUE #35: [Feature Request] Hide/Show the Header
Hi,
the header is consuming too much space. Can you add a button for that?

image

image

The snippet would be something like:

```
<header x-data="{ open: false }">
    <button @click="open = !open">Toggle Header</button>
    <div x-show="open">
        <h1 class=inline_centre style="margin: 0; margin-top: 0.3ch;"><img src="img/osm.png" alt="OpenStreetMap logo" style="height: 1em"><span>🏞️ WaterwayMap</span></h1>
        <!-- Rest of your header content goes here -->
        
        <!-- ... -->

        <!-- Make sure all content you want to be collapsible is wrapped in this div with x-show directive -->
    </div>
</header>
```

I tested the snipped, it works in the Dev Tools.
BR Günther

### LINKED ISSUE #37: bigger screen or full displaying needed
Thanks for your great job. I love it.
I wish a bigger displaying because the map is shown almost half the screen.

### PR DESCRIPTION
**Pull request by mxdanger**
At the moment it's not 100% functional and more work is needed.

Resolves #37, closes #35 

See draft #40 

Mark for review before merge

### CODE REVIEW

**Comment by mxdanger** [comment]
- [ ] Add settings modal sub menu button functionality
- [ ] Fix settings way color
- [ ] Fix share geo URI text not updating
- [ ] Fix Share link
- [ ] Add color scheme toggle for auto, dark, light
- [ ] Add UI for ends and loops
- [ ] Set default edit button when dropdown selected

**Comment by mxdanger** [comment]
What are useful links to use for Help and About?

Here is an example:
- Help could link to the OSM wiki page for waterways.
- About could just be a simple page for contact information, contributors and other social links.

**Comment by amandasaurus** [comment]
The `Edit` button should remember what editor you used, or in the best case, somehow use your OSM preferences. However that's a new feature. Since I want to often use JOSM, not just iD, and I don't want to have that behind a few clicks. I've added 2 `Edit` buttons for iD & JOSM.

**Comment by amandasaurus** [comment]
On the `/help` & `/about` page, the navbar is covering the start of the `<main>`. What's going on here? (I don't know enough Bootstrap to be sure)

image

**Comment by mxdanger** [comment]
> The `Edit` button should remember what editor you used, or in the best case, somehow use your OSM preferences. However that's a new feature. Since I want to often use JOSM, not just iD, and I don't want to have that behind a few clicks. I've added 2 `Edit` buttons for iD & JOSM.

It's fine if we don't add the feature but I think the UI should still be the same as the OSM website at least, rather than overload the user with many choices for edit buttons. Later we could add an option in settings to set the default (and/or remember what the user picked from the dropdown) but for the time being having the default be iD as that's what most users prefer, would be the better way to go.

**Comment by mxdanger** [comment]
LGTM

**Pull request merged**
